// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	v1alpha1 "k8s.io/api/extensions/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	core "k8s.io/kubernetes/pkg/apis/core"
	extensions "k8s.io/kubernetes/pkg/apis/extensions"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ExtendedResource_To_extensions_ExtendedResource,
		Convert_extensions_ExtendedResource_To_v1alpha1_ExtendedResource,
		Convert_v1alpha1_ExtendedResourceClaim_To_extensions_ExtendedResourceClaim,
		Convert_extensions_ExtendedResourceClaim_To_v1alpha1_ExtendedResourceClaim,
		Convert_v1alpha1_ExtendedResourceClaimList_To_extensions_ExtendedResourceClaimList,
		Convert_extensions_ExtendedResourceClaimList_To_v1alpha1_ExtendedResourceClaimList,
		Convert_v1alpha1_ExtendedResourceClaimSpec_To_extensions_ExtendedResourceClaimSpec,
		Convert_extensions_ExtendedResourceClaimSpec_To_v1alpha1_ExtendedResourceClaimSpec,
		Convert_v1alpha1_ExtendedResourceClaimStatus_To_extensions_ExtendedResourceClaimStatus,
		Convert_extensions_ExtendedResourceClaimStatus_To_v1alpha1_ExtendedResourceClaimStatus,
		Convert_v1alpha1_ExtendedResourceList_To_extensions_ExtendedResourceList,
		Convert_extensions_ExtendedResourceList_To_v1alpha1_ExtendedResourceList,
		Convert_v1alpha1_ExtendedResourceSpec_To_extensions_ExtendedResourceSpec,
		Convert_extensions_ExtendedResourceSpec_To_v1alpha1_ExtendedResourceSpec,
		Convert_v1alpha1_ExtendedResourceStatus_To_extensions_ExtendedResourceStatus,
		Convert_extensions_ExtendedResourceStatus_To_v1alpha1_ExtendedResourceStatus,
		Convert_v1alpha1_ResourceNodeAffinity_To_extensions_ResourceNodeAffinity,
		Convert_extensions_ResourceNodeAffinity_To_v1alpha1_ResourceNodeAffinity,
	)
}

func autoConvert_v1alpha1_ExtendedResource_To_extensions_ExtendedResource(in *v1alpha1.ExtendedResource, out *extensions.ExtendedResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ExtendedResourceSpec_To_extensions_ExtendedResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ExtendedResourceStatus_To_extensions_ExtendedResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ExtendedResource_To_extensions_ExtendedResource is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResource_To_extensions_ExtendedResource(in *v1alpha1.ExtendedResource, out *extensions.ExtendedResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResource_To_extensions_ExtendedResource(in, out, s)
}

func autoConvert_extensions_ExtendedResource_To_v1alpha1_ExtendedResource(in *extensions.ExtendedResource, out *v1alpha1.ExtendedResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_extensions_ExtendedResourceSpec_To_v1alpha1_ExtendedResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_extensions_ExtendedResourceStatus_To_v1alpha1_ExtendedResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_extensions_ExtendedResource_To_v1alpha1_ExtendedResource is an autogenerated conversion function.
func Convert_extensions_ExtendedResource_To_v1alpha1_ExtendedResource(in *extensions.ExtendedResource, out *v1alpha1.ExtendedResource, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResource_To_v1alpha1_ExtendedResource(in, out, s)
}

func autoConvert_v1alpha1_ExtendedResourceClaim_To_extensions_ExtendedResourceClaim(in *v1alpha1.ExtendedResourceClaim, out *extensions.ExtendedResourceClaim, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ExtendedResourceClaimSpec_To_extensions_ExtendedResourceClaimSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ExtendedResourceClaimStatus_To_extensions_ExtendedResourceClaimStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ExtendedResourceClaim_To_extensions_ExtendedResourceClaim is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResourceClaim_To_extensions_ExtendedResourceClaim(in *v1alpha1.ExtendedResourceClaim, out *extensions.ExtendedResourceClaim, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResourceClaim_To_extensions_ExtendedResourceClaim(in, out, s)
}

func autoConvert_extensions_ExtendedResourceClaim_To_v1alpha1_ExtendedResourceClaim(in *extensions.ExtendedResourceClaim, out *v1alpha1.ExtendedResourceClaim, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_extensions_ExtendedResourceClaimSpec_To_v1alpha1_ExtendedResourceClaimSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_extensions_ExtendedResourceClaimStatus_To_v1alpha1_ExtendedResourceClaimStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_extensions_ExtendedResourceClaim_To_v1alpha1_ExtendedResourceClaim is an autogenerated conversion function.
func Convert_extensions_ExtendedResourceClaim_To_v1alpha1_ExtendedResourceClaim(in *extensions.ExtendedResourceClaim, out *v1alpha1.ExtendedResourceClaim, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResourceClaim_To_v1alpha1_ExtendedResourceClaim(in, out, s)
}

func autoConvert_v1alpha1_ExtendedResourceClaimList_To_extensions_ExtendedResourceClaimList(in *v1alpha1.ExtendedResourceClaimList, out *extensions.ExtendedResourceClaimList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]extensions.ExtendedResourceClaim)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ExtendedResourceClaimList_To_extensions_ExtendedResourceClaimList is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResourceClaimList_To_extensions_ExtendedResourceClaimList(in *v1alpha1.ExtendedResourceClaimList, out *extensions.ExtendedResourceClaimList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResourceClaimList_To_extensions_ExtendedResourceClaimList(in, out, s)
}

func autoConvert_extensions_ExtendedResourceClaimList_To_v1alpha1_ExtendedResourceClaimList(in *extensions.ExtendedResourceClaimList, out *v1alpha1.ExtendedResourceClaimList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.ExtendedResourceClaim)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_extensions_ExtendedResourceClaimList_To_v1alpha1_ExtendedResourceClaimList is an autogenerated conversion function.
func Convert_extensions_ExtendedResourceClaimList_To_v1alpha1_ExtendedResourceClaimList(in *extensions.ExtendedResourceClaimList, out *v1alpha1.ExtendedResourceClaimList, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResourceClaimList_To_v1alpha1_ExtendedResourceClaimList(in, out, s)
}

func autoConvert_v1alpha1_ExtendedResourceClaimSpec_To_extensions_ExtendedResourceClaimSpec(in *v1alpha1.ExtendedResourceClaimSpec, out *extensions.ExtendedResourceClaimSpec, s conversion.Scope) error {
	out.MetadataRequirements = in.MetadataRequirements
	out.ExtendedResourceNames = *(*[]string)(unsafe.Pointer(&in.ExtendedResourceNames))
	out.RawResourceName = in.RawResourceName
	out.ExtendedResourceNum = in.ExtendedResourceNum
	return nil
}

// Convert_v1alpha1_ExtendedResourceClaimSpec_To_extensions_ExtendedResourceClaimSpec is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResourceClaimSpec_To_extensions_ExtendedResourceClaimSpec(in *v1alpha1.ExtendedResourceClaimSpec, out *extensions.ExtendedResourceClaimSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResourceClaimSpec_To_extensions_ExtendedResourceClaimSpec(in, out, s)
}

func autoConvert_extensions_ExtendedResourceClaimSpec_To_v1alpha1_ExtendedResourceClaimSpec(in *extensions.ExtendedResourceClaimSpec, out *v1alpha1.ExtendedResourceClaimSpec, s conversion.Scope) error {
	out.MetadataRequirements = in.MetadataRequirements
	out.ExtendedResourceNames = *(*[]string)(unsafe.Pointer(&in.ExtendedResourceNames))
	out.RawResourceName = in.RawResourceName
	out.ExtendedResourceNum = in.ExtendedResourceNum
	return nil
}

// Convert_extensions_ExtendedResourceClaimSpec_To_v1alpha1_ExtendedResourceClaimSpec is an autogenerated conversion function.
func Convert_extensions_ExtendedResourceClaimSpec_To_v1alpha1_ExtendedResourceClaimSpec(in *extensions.ExtendedResourceClaimSpec, out *v1alpha1.ExtendedResourceClaimSpec, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResourceClaimSpec_To_v1alpha1_ExtendedResourceClaimSpec(in, out, s)
}

func autoConvert_v1alpha1_ExtendedResourceClaimStatus_To_extensions_ExtendedResourceClaimStatus(in *v1alpha1.ExtendedResourceClaimStatus, out *extensions.ExtendedResourceClaimStatus, s conversion.Scope) error {
	out.Phase = extensions.ExtendedResourceClaimPhase(in.Phase)
	out.Message = in.Message
	out.Reason = in.Reason
	return nil
}

// Convert_v1alpha1_ExtendedResourceClaimStatus_To_extensions_ExtendedResourceClaimStatus is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResourceClaimStatus_To_extensions_ExtendedResourceClaimStatus(in *v1alpha1.ExtendedResourceClaimStatus, out *extensions.ExtendedResourceClaimStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResourceClaimStatus_To_extensions_ExtendedResourceClaimStatus(in, out, s)
}

func autoConvert_extensions_ExtendedResourceClaimStatus_To_v1alpha1_ExtendedResourceClaimStatus(in *extensions.ExtendedResourceClaimStatus, out *v1alpha1.ExtendedResourceClaimStatus, s conversion.Scope) error {
	out.Phase = v1alpha1.ExtendedResourceClaimPhase(in.Phase)
	out.Message = in.Message
	out.Reason = in.Reason
	return nil
}

// Convert_extensions_ExtendedResourceClaimStatus_To_v1alpha1_ExtendedResourceClaimStatus is an autogenerated conversion function.
func Convert_extensions_ExtendedResourceClaimStatus_To_v1alpha1_ExtendedResourceClaimStatus(in *extensions.ExtendedResourceClaimStatus, out *v1alpha1.ExtendedResourceClaimStatus, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResourceClaimStatus_To_v1alpha1_ExtendedResourceClaimStatus(in, out, s)
}

func autoConvert_v1alpha1_ExtendedResourceList_To_extensions_ExtendedResourceList(in *v1alpha1.ExtendedResourceList, out *extensions.ExtendedResourceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]extensions.ExtendedResource)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ExtendedResourceList_To_extensions_ExtendedResourceList is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResourceList_To_extensions_ExtendedResourceList(in *v1alpha1.ExtendedResourceList, out *extensions.ExtendedResourceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResourceList_To_extensions_ExtendedResourceList(in, out, s)
}

func autoConvert_extensions_ExtendedResourceList_To_v1alpha1_ExtendedResourceList(in *extensions.ExtendedResourceList, out *v1alpha1.ExtendedResourceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.ExtendedResource)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_extensions_ExtendedResourceList_To_v1alpha1_ExtendedResourceList is an autogenerated conversion function.
func Convert_extensions_ExtendedResourceList_To_v1alpha1_ExtendedResourceList(in *extensions.ExtendedResourceList, out *v1alpha1.ExtendedResourceList, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResourceList_To_v1alpha1_ExtendedResourceList(in, out, s)
}

func autoConvert_v1alpha1_ExtendedResourceSpec_To_extensions_ExtendedResourceSpec(in *v1alpha1.ExtendedResourceSpec, out *extensions.ExtendedResourceSpec, s conversion.Scope) error {
	out.NodeAffinity = (*extensions.ResourceNodeAffinity)(unsafe.Pointer(in.NodeAffinity))
	out.RawResourceName = in.RawResourceName
	out.DeviceID = in.DeviceID
	out.Properties = *(*map[string]string)(unsafe.Pointer(&in.Properties))
	out.ExtendedResourceClaimName = in.ExtendedResourceClaimName
	return nil
}

// Convert_v1alpha1_ExtendedResourceSpec_To_extensions_ExtendedResourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResourceSpec_To_extensions_ExtendedResourceSpec(in *v1alpha1.ExtendedResourceSpec, out *extensions.ExtendedResourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResourceSpec_To_extensions_ExtendedResourceSpec(in, out, s)
}

func autoConvert_extensions_ExtendedResourceSpec_To_v1alpha1_ExtendedResourceSpec(in *extensions.ExtendedResourceSpec, out *v1alpha1.ExtendedResourceSpec, s conversion.Scope) error {
	out.NodeAffinity = (*v1alpha1.ResourceNodeAffinity)(unsafe.Pointer(in.NodeAffinity))
	out.RawResourceName = in.RawResourceName
	out.DeviceID = in.DeviceID
	out.Properties = *(*map[string]string)(unsafe.Pointer(&in.Properties))
	out.ExtendedResourceClaimName = in.ExtendedResourceClaimName
	return nil
}

// Convert_extensions_ExtendedResourceSpec_To_v1alpha1_ExtendedResourceSpec is an autogenerated conversion function.
func Convert_extensions_ExtendedResourceSpec_To_v1alpha1_ExtendedResourceSpec(in *extensions.ExtendedResourceSpec, out *v1alpha1.ExtendedResourceSpec, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResourceSpec_To_v1alpha1_ExtendedResourceSpec(in, out, s)
}

func autoConvert_v1alpha1_ExtendedResourceStatus_To_extensions_ExtendedResourceStatus(in *v1alpha1.ExtendedResourceStatus, out *extensions.ExtendedResourceStatus, s conversion.Scope) error {
	out.Capacity = in.Capacity
	out.Allocatable = in.Allocatable
	out.Phase = extensions.ExtendedResourcePhase(in.Phase)
	out.Message = in.Message
	out.Reason = in.Reason
	return nil
}

// Convert_v1alpha1_ExtendedResourceStatus_To_extensions_ExtendedResourceStatus is an autogenerated conversion function.
func Convert_v1alpha1_ExtendedResourceStatus_To_extensions_ExtendedResourceStatus(in *v1alpha1.ExtendedResourceStatus, out *extensions.ExtendedResourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtendedResourceStatus_To_extensions_ExtendedResourceStatus(in, out, s)
}

func autoConvert_extensions_ExtendedResourceStatus_To_v1alpha1_ExtendedResourceStatus(in *extensions.ExtendedResourceStatus, out *v1alpha1.ExtendedResourceStatus, s conversion.Scope) error {
	out.Capacity = in.Capacity
	out.Allocatable = in.Allocatable
	out.Phase = v1alpha1.ExtendedResourcePhase(in.Phase)
	out.Message = in.Message
	out.Reason = in.Reason
	return nil
}

// Convert_extensions_ExtendedResourceStatus_To_v1alpha1_ExtendedResourceStatus is an autogenerated conversion function.
func Convert_extensions_ExtendedResourceStatus_To_v1alpha1_ExtendedResourceStatus(in *extensions.ExtendedResourceStatus, out *v1alpha1.ExtendedResourceStatus, s conversion.Scope) error {
	return autoConvert_extensions_ExtendedResourceStatus_To_v1alpha1_ExtendedResourceStatus(in, out, s)
}

func autoConvert_v1alpha1_ResourceNodeAffinity_To_extensions_ResourceNodeAffinity(in *v1alpha1.ResourceNodeAffinity, out *extensions.ResourceNodeAffinity, s conversion.Scope) error {
	out.Required = (*core.NodeSelector)(unsafe.Pointer(in.Required))
	return nil
}

// Convert_v1alpha1_ResourceNodeAffinity_To_extensions_ResourceNodeAffinity is an autogenerated conversion function.
func Convert_v1alpha1_ResourceNodeAffinity_To_extensions_ResourceNodeAffinity(in *v1alpha1.ResourceNodeAffinity, out *extensions.ResourceNodeAffinity, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceNodeAffinity_To_extensions_ResourceNodeAffinity(in, out, s)
}

func autoConvert_extensions_ResourceNodeAffinity_To_v1alpha1_ResourceNodeAffinity(in *extensions.ResourceNodeAffinity, out *v1alpha1.ResourceNodeAffinity, s conversion.Scope) error {
	out.Required = (*v1.NodeSelector)(unsafe.Pointer(in.Required))
	return nil
}

// Convert_extensions_ResourceNodeAffinity_To_v1alpha1_ResourceNodeAffinity is an autogenerated conversion function.
func Convert_extensions_ResourceNodeAffinity_To_v1alpha1_ResourceNodeAffinity(in *extensions.ResourceNodeAffinity, out *v1alpha1.ResourceNodeAffinity, s conversion.Scope) error {
	return autoConvert_extensions_ResourceNodeAffinity_To_v1alpha1_ResourceNodeAffinity(in, out, s)
}
